### ISSUE TITLE
When running action it throws fatal: unable to access '[repo url]': URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by gzuzmark** [one-aalam/github-action-astro-publish-drafts#237]
Issue Summary
When running action it throws fatal: unable to access '[repo url]': URL using bad/illegal format or missing URL

Steps to Reproduce
1. It was previously workingcorrectly in my repo. I using astro/ink(Than you for your work by the way)
2. If you have any clue what could be wrong let me know.

![24 11 2022_12 31 14_REC](https://user-images.githubusercontent.com/5327036/203840826-8c6d0c2d-d01e-4b39-9b64-a5e604e1d4b0.png)

this is my yaml

```
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 30 */4 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-drafts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSG Publish Drafts
        # You may pin to the exact commit or the version.
        uses: one-aalam/github-action-ssg-publish-drafts@v0.1-beta
        with:
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          github_actor: gzuzmark
          github_repository: gzuzmark/jesusdeva
```
